### ISSUE TITLE
AMOLED Theme

### ISSUE THREAD

**Issue by lance36** [home-assistant-community-themes/theme-request#1]
# General information

**Owner**

[lance36](https://github.com/lance36/)

**Name**

Amoled

**Post link**

https://github.com/maartenpaauw/home-assistant-community-themes/pull/2

**Funding**

https://www.paypal.me/k3png

# Screenshot(s)

https://i.imgur.com/ArcMnlY.png

# Source

```yaml
amoled:
  primary-color: "#484A4C"
  accent-color: "#E45E65"
  dark-primary-color: "var(--accent-color)"
  light-primary-color: "var(--accent-color)"
  primary-text-color: "#FFFFFF"
  text-primary-color: "var(--primary-text-color)"
  secondary-text-color: "#5294E2"
  disabled-text-color: "#7F848E"
  label-badge-border-color: "green"
  primary-background-color: "#000000"
  secondary-background-color: "#383C45"
  sidebar-text-color: "var(--primary-color)"
  sidebar-icon-color: "var(--primary-color)"
  sidebar-selected-text-color: "var(--primary-text-color)"
  sidebar-selected-icon-color: "var(--primary-text-color)"
  divider-color: "rgba(0, 0, 0, .12)"
  table-row-background-color: "#353840"
  table-row-alternative-background-color: "#3E424B"
  paper-listbox-color: "#FFFFFF)"
  paper-listbox-background-color: "#000000"
  paper-grey-50: "var(--primary-text-color)"
  paper-grey-200: "#414A59"
  paper-card-header-color: "var(--accent-color)"
  paper-card-background-color: "#000000"
  paper-dialog-background-color: "#000000"
  paper-item-icon-color: "var(--primary-text-color)"
  paper-item-icon-active-color: "#F9C536"
  paper-item-icon_-_color: "green"
  paper-item-selected_-_background-color: "#434954"
  paper-tabs-selection-bar-color: "green"
  label-badge-red: "var(--accent-color)"
  label-badge-text-color: "var(--primary-text-color)"
  label-badge-background-color: "#2E333A"
  paper-button-ink-color: "#5294E2"
  paper-button-color: "#5294E2"
  paper-toggle-button-checked-button-color: "var(--accent-color)"
  paper-toggle-button-checked-bar-color: "var(--accent-color)"
  paper-toggle-button-checked-ink-color: "var(--accent-color)"
  paper-toggle-button-unchecked-button-color: "var(--disabled-text-color)"
  paper-toggle-button-unchecked-bar-color: "var(--disabled-text-color)"
  paper-toggle-button-unchecked-ink-color: "var(--disabled-text-color)"
  paper-slider-knob-color: "var(--accent-color)"
  paper-slider-knob-start-color: "var(--accent-color)"
  paper-slider-pin-color: "var(--accent-color)"
  paper-slider-active-color: "var(--accent-color)"
  paper-slider-container-color: "linear-gradient(var(--primary-background-color), var(--secondary-background-color)) no-repeat"
  paper-slider-secondary-color: "var(--secondary-background-color)"
  paper-slider-disabled-active-color: "var(--disabled-text-color)"
  paper-slider-disabled-secondary-color: "var(--disabled-text-color)"
  google-red-500: "#E45E65"
  google-green-500: "#39E949"

```
