### ISSUE TITLE
Stell Blue with Colors Theme

### ISSUE THREAD

**Issue by joselito11** [home-assistant-community-themes/theme-request#6]
# General information

**Owner**

https://github.com/joselito11

**Name**

Stell Blue with Colors Theme

**Post link**

https://github.com/joselito11/home-assistant

# Screenshot(s)

![Zaslonska slika 2020-01-25 12-13-12](https://user-images.githubusercontent.com/53316474/73120850-4d5dc000-3f73-11ea-887b-38d5a0b8c7f1.png)
![Zaslonska slika 2020-01-25 12-13-35](https://user-images.githubusercontent.com/53316474/73120851-4d5dc000-3f73-11ea-90cb-396bb5859001.png)
![Zaslonska slika 2020-01-25 12-14-33](https://user-images.githubusercontent.com/53316474/73120852-4d5dc000-3f73-11ea-9a2c-3ae2f2564ef3.png)
![Zaslonska slika 2020-01-25 12-14-59](https://user-images.githubusercontent.com/53316474/73120853-4d5dc000-3f73-11ea-8293-9bd715712f87.png)
![Zaslonska slika 2020-01-25 12-15-31](https://user-images.githubusercontent.com/53316474/73120854-4df65680-3f73-11ea-883b-7c9b8db7fc35.png)
![Zaslonska slika 2020-01-25 12-15-41](https://user-images.githubusercontent.com/53316474/73120856-4df65680-3f73-11ea-91a9-5368875b203c.png)
![Zaslonska slika 2020-01-25 12-15-59](https://user-images.githubusercontent.com/53316474/73120857-4df65680-3f73-11ea-9a39-9b31dfa2c08d.png)
![Zaslonska slika 2020-01-25 12-16-32](https://user-images.githubusercontent.com/53316474/73120859-4e8eed00-3f73-11ea-8eb1-97d1b9422f39.png)

# Source
https://github.com/joselito11/home-assistant/blob/master/themes/DarkSteelBlueColors.yaml

```
DarkSteelBlueColors:
  text-color: "white"
  text-medium-light-color: "orange"
  text-medium-color: "olivedrab"
  text-dark-color: "olivedrab"
  accent-color: "crimson"
  accent-medium-color: "crimson"
  background-color: "#484E59"
  background-color-2: "#484E59"
  background-card-color: "#4f5663"
  border-color: "red"
  primary-color: "steelblue"
  text-primary-color: "white"
  paper-listbox-background-color: "#4f5663"
  sidebar-icon-color: "steelblue"
  sidebar-selected-icon-color: "lightsteelblue"
  sidebar-selected-text-color: "lightsteelblue"
  paper-card-header-color: "red"
  primary-background-color: "var(--background-color)"
  mdc-theme-primary: "var(--accent-medium-color)"
  paper-card-background-color: "var(--background-card-color)"
  dark-primary-color: "var(--text-color)"
  primary-text-color: "#e1e1e3"
  paper-listbox-color: "yellow"
  light-primary-color: "steelblue"
  secondary-text-color: "olivedrab"
  disabled-text-color: "BlueViolet "
  paper-dialog-button-color: "yellow"
  secondary-background-color: "var(--background-color-2)"
  paper-item-icon-color: "steelblue"
  paper-item-icon-active-color: "darkorange"
  paper-toggle-button-checked-button-color: "olivedrab"
  paper-toggle-button-checked-bar-color: "darkgray"
  paper-toggle-button-unchecked-button-color: "IndianRed  "
  paper-toggle-button-unchecked-bar-color: "#767682"
  shadow-elevation-2dp_-_box-shadow: "inset 0px 0px 0px 1px var(--border-color)"
  shadow-elevation-4dp_-_box-shadow: "var(--shadow-elevation-2dp_-_box-shadow)"
  shadow-elevation-6dp_-_box-shadow: "var(--shadow-elevation-2dp_-_box-shadow)"
  shadow-elevation-8dp_-_box-shadow: "var(--shadow-elevation-2dp_-_box-shadow)"
  shadow-elevation-10dp_-_box-shadow: "var(--shadow-elevation-2dp_-_box-shadow)"
  shadow-elevation-12dp_-_box-shadow: "var(--shadow-elevation-2dp_-_box-shadow)"
  shadow-elevation-14dp_-_box-shadow: "var(--shadow-elevation-2dp_-_box-shadow)"
  shadow-elevation-16dp_-_box-shadow: "0px 0px 0px 3px var(--text-dark-color)"

```
