### ISSUE TITLE
Solarized Dark

### ISSUE THREAD

**Issue by bonanitech** [home-assistant-community-themes/theme-request#7]
# General information

**Owner**

DouglasK - https://community.home-assistant.io/u/douglask1

**Name**

Solarized Dark

**Post link**

https://community.home-assistant.io/t/solarized-dark/77403

![](https://community-home-assistant-assets.s3.dualstack.us-west-2.amazonaws.com/original/3X/9/3/9350714f67edd65a52d45dd8e104226ff79937fa.png)

**Funding**

# Screenshot(s)

![9350714f67edd65a52d45dd8e104226ff79937fa](https://user-images.githubusercontent.com/29807944/75194394-07d51400-5726-11ea-89e7-990d246e607c.png)

# Source

```yaml
solarized_dark:
  primary-color: "#586e75"
  accent-color: "#002b36"
  dark-primary-color: "#93a1a1"
  light-primary-color: "var(--accent-color)"
  primary-text-color: "#839496"
  text-primary-color: "var(--primary-text-color)"
  secondary-text-color: "#586e75"
  disabled-text-color: "#7F848E"
  label-badge-border-color: "green"
  primary-background-color: "#002b36"
  secondary-background-color: "#073642"
  divider-color: "rgba(0, 0, 0, .12)"
  table-row-background-color: "#002b36"
  table-row-alternative-background-color: "#073642"
  paper-listbox-color: "var(--primary-color)"
  paper-listbox-background-color: "var(--accent-color)"
  paper-grey-50: "var(--primary-text-color)"
  paper-grey-200: "var(--accent-color)"
  paper-card-header-color: "var(--dark-primary-color)"
  paper-card-background-color: "var(--accent-color)"
  paper-dialog-background-color: "#002b36"
  paper-item-icon-color: "var(--primary-text-color)"
  paper-item-icon-active-color: "#b58900"
  paper-item-icon_-_color: "#859900"
  paper-item-selected_-_color: "var(--accent-color)"
  paper-item-selected_-_background-color: "#cb4b16"
  paper-tabs-selection-bar-color: "#859900"
  label-badge-red: "#93a1a1"
  label-badge-text-color: "var(--primary-text-color)"
  label-badge-background-color: "var(--accent-color)"
  paper-toggle-button-checked-button-color: "#268bd2"
  paper-toggle-button-checked-bar-color: "var(--primary-color)"
  paper-toggle-button-checked-ink-color: "#268bd2"
  paper-toggle-button-unchecked-button-color: "var(--secondary-background-color)"
  paper-toggle-button-unchecked-bar-color: "var(--secondary-text-color)"
  paper-toggle-button-unchecked-ink-color: "var(--secondary-background-color)"
  paper-slider-knob-color: "var(--secondary-text-color)"
  paper-slider-knob-start-color: "var(--secondary-text-color)"
  paper-slider-pin-color: "var(--secondary-text-color)"
  paper-slider-active-color: "var(--secondary-text-color)"
  paper-slider-container-color: "linear-gradient(var(--primary-background-color), var(--secondary-background-color)) no-repeat"
  paper-slider-secondary-color: "var(--secondary-background-color)"
  paper-slider-disabled-active-color: "var(--disabled-text-color)"
  paper-slider-disabled-secondary-color: "var(--disabled-text-color)"
  sidebar-selected-icon-color: 'var(--secondary-text-color)'
  sidebar-icon-color: 'var(--primary-text-color)'
  google-red-500: "#dc322f"
  google-green-500: "#859900"
```
