### ISSUE TITLE
Nord Theme

### ISSUE THREAD

**Issue by jasperro** [home-assistant-community-themes/theme-request#8]
# General information

**Owner**

Jasperro - https://github.com/jasperro, https://community.home-assistant.io/u/jasperro/

**Name**

Nord

**Post link**

https://community.home-assistant.io/t/nord-theme/129301

**Description**
This theme is based on the Nord colors from [nordtheme.com](https://www.nordtheme.com/), and offers multiple accent colors to choose from.

# Screenshot(s)

https://imgur.com/a/X4ScUSq

# Source

```yaml
nord:
  # Color Setup
  light-background-color: "#3b4252"
  lighter-background-color: "#454c5f"
  dark-background-color: "#2E3440"
  card-background-color: "#4c566a"
  foreground-color: "#eceff4"
  #accent-color: "#8fbcbb" # Nord7 - calm blue
  #accent-color: "#88c0d0" # Nord8 - bright blue
  accent-color: "#81a1c1" # Nord9  - muted blue (default)
  #accent-color: "#5e81ac" # Nord10 - blue
  #accent-color: "#bf616a" # Nord11 - red
  #accent-color: "#d08770" # Nord12 - orange
  #accent-color: "#ebcb8b" # Nord13 - yellow
  #accent-color: "#a3be8c" # Nord14 - green
  #accent-color: "#b48ead" # Nord15 - purple
  

  primary-color: "var(--accent-color)"
  light-primary-color: "var(--dark-background-color)"
  primary-background-color: "var(--dark-background-color)"
  secondary-background-color: "var(--dark-background-color)"
  divider-color: "var(--dark-background-color)"

  paper-grey-50: "var(--accent-color)"
  paper-grey-200: "var(--dark-background-color)"

  primary-text-color: "var(--foreground-color)"
  secondary-text-color: "var(--foreground-color)"
  disabled-text-color: "var(--light-background-color)"
  light-disabled-text-color: "var(--lighter-background-color)"
  dark-primary-color: "var(--accent-color)"

  # Interface
  ha-card-border-radius: "0px"
  primary-font-family: "Roboto Condensed, Roboto, system-ui"

  # Paper
  paper-card-background-color: "var(--card-background-color)"
  paper-card-header-color: "var(--accent-color)"

  paper-listbox-background-color: "var(--light-background-color)"
  paper-listbox-color: "var(--accent-color)"

  paper-item-selected_-_background-color: "var(--dark-background-color)"
  paper-item-icon-color: "var(--foreground-color)"
  paper-item-icon_-_color: "var(--foreground-color)"
  paper-item-icon-active-color: "var(--accent-color)"

  # Label-badge
  label-badge-text-color: "var(--foreground-color)"
  label-badge-background-color: "var(--card-background-color)"
  label-badge-red: "var(--accent-color)"

  # Slider
  paper-slider-active-color: "var(--accent-color)"
  paper-slider-secondary-color: "var(--accent-color)"
  paper-slider-knob-color: "var(--accent-color)"
  paper-slider-knob-start-color: "var(--accent-color)"
  paper-slider-pin-color: "var(--accent-color)"

  # Toggle
  paper-toggle-button-unchecked-bar-color: "var(--accent-color)"
  paper-toggle-button-unchecked-button-color: "var(--accent-color)"
  paper-toggle-button-unchecked-ink-color: "var(--accent-color)"

  paper-toggle-button-checked-bar-color: "var(--accent-color)"
  paper-toggle-button-checked-button-color: "var(--accent-color)"

  # Switch
  switch-unchecked-track-color: "var(--disabled-text-color)"
  switch-unchecked-color: "var(--light-disabled-text-color)"

  switch-checked-track-color: "var(--accent-color)"
  switch-checked-color: "var(--accent-color)"

  # Font Settings
  paper-font-common-base_-_font-family: "var(--primary-font-family)"
  paper-font-common-code_-_font-family: "var(--primary-font-family)"
  paper-font-body1_-_font-family: "var(--primary-font-family)"
  paper-font-subhead_-_font-family: "var(--primary-font-family)"
  paper-font-headline_-_font-family: "var(--primary-font-family)"
  paper-font-caption_-_font-family: "var(--primary-font-family)"
  paper-font-title_-_font-family: "var(--primary-font-family)"
  ha-card-header-font-family: "var(--primary-font-family)"
  ha-card-header-color: "var(--foreground-color)"

  # Other
  sidebar-icon-color: "var(--foreground-color)"
  sidebar-background-color: "var(--light-background-color)"
```
